max_retries: 10
schedule:
  enqueue_notifications:
    cron: '0 * * * *' # every hour
    class: "Presentation::Jobs::EnqueueNotifications"
  enqueue_crawlers:
    cron: '45 0/6 * * *' # 4 times a day
    class: "Presentation::Jobs::EnqueueCrawlers"
  kill_selenium:
    cron: '0 0 * * *' # every day at 00:00 AM
    class: "Presentation::Jobs::KillSelenium"
